version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: unkflixcontainer
    environment:
      POSTGRES_DB: 'unkflix'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5401:5432"
    restart: always